POST http://localhost:3030/api/v0/json-rpc/ HTTP/1.1
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "get_metadatas",
    "params": ["0c2437d898045ee74fb3f0e732e1e2a1edc73b761f8168d466b43a3507fc17c2"],
    "id": "string"
}